<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Yi(Ryan) Zhao">
<meta name="dcterms.date" content="2026-05-28">

<title>HW4-MaxDiff Analysis of MSBA Class Preferences – Yi(Ryan) Zhao</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-a0f9fd0d421825b736dc1bbcbcba2219.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Yi(Ryan) Zhao</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resume.html"> 
<span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#the-data" id="toc-the-data" class="nav-link" data-scroll-target="#the-data">The Data</a></li>
  <li><a href="#counts-analysis" id="toc-counts-analysis" class="nav-link" data-scroll-target="#counts-analysis">Counts Analysis</a></li>
  <li><a href="#from-maxdiff-data-to-mnl-choices" id="toc-from-maxdiff-data-to-mnl-choices" class="nav-link" data-scroll-target="#from-maxdiff-data-to-mnl-choices">From MaxDiff Data to MNL Choices</a></li>
  <li><a href="#mnl-via-maximum-likelihood" id="toc-mnl-via-maximum-likelihood" class="nav-link" data-scroll-target="#mnl-via-maximum-likelihood">MNL via Maximum Likelihood</a></li>
  <li><a href="#mnl-via-bayesian-estimation" id="toc-mnl-via-bayesian-estimation" class="nav-link" data-scroll-target="#mnl-via-bayesian-estimation">MNL via Bayesian Estimation</a></li>
  <li><a href="#comparing-the-three-methods" id="toc-comparing-the-three-methods" class="nav-link" data-scroll-target="#comparing-the-three-methods">Comparing the Three Methods</a></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">HW4-MaxDiff Analysis of MSBA Class Preferences</h1>
<p class="subtitle lead">Counts, MLE, and Bayesian estimation of the MNL model</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Yi(Ryan) Zhao </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 28, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>MaxDiff, or Best-Worst Scaling, is a survey method for measuring relative preferences across a set of items. On each screen, respondents see a small subset of items and identify the one they like most and the one they like least. Repeating this over many screens produces data that are much more informative than simple rating scales, because respondents are forced to make trade-offs rather than assigning similar scores to many items.</p>
<p>In this assignment, I analyze MaxDiff responses about 10 core MSBA classes. I begin with a simple counts-based summary using net best-minus-worst scores, then estimate a multinomial logit (MNL) model by maximum likelihood, and finally compare those estimates with a Bayesian MAP version of the same model. The goal is to see how the three approaches differ and whether they lead to the same substantive ranking of class preferences.</p>
</section>
<section id="the-data" class="level2">
<h2 class="anchored" data-anchor-id="the-data">The Data</h2>
<p>The raw MaxDiff file records one row per item shown on a respondent-task screen. Each row identifies the respondent, the task number, the position of the item on the screen, the item shown, and whether that item was selected as best, worst, or neither. The item-label file maps numeric item codes to the corresponding MSBA class names.</p>
<p>One complication is that the raw file contains two kinds of tasks. Tasks 1 through 8 follow the standard MaxDiff format with 4 items shown per screen, while later tasks contain only 2 items and include an additional item code not present in the class-label file. Because the assignment is framed around the 10 core classes and 4-item MaxDiff screens, I restrict the analysis to Tasks 1–8, which yields a clean 10-item MaxDiff dataset.</p>
<p>After this restriction, the study contains 85 respondents, each completing 8 tasks with 4 items per task, for a total of 10 classes in the analysis. A sanity check confirms that every task contains exactly one best choice, one worst choice, and two unselected items. Exposure counts are also roughly balanced across classes, which is what we would expect from a well-constructed MaxDiff design.</p>
</section>
<section id="counts-analysis" class="level2">
<h2 class="anchored" data-anchor-id="counts-analysis">Counts Analysis</h2>
<p>As a simple aggregate summary, I first compute how often each class is selected as best and as worst across all screens in which it appears. Following the basic MaxDiff summary introduced in class, I then calculate a net score equal to the percentage of times an item is chosen best minus the percentage of times it is chosen worst. This measure is easy to interpret, though it is still only a descriptive summary rather than a full statistical model.</p>
<div id="cell-counts-summary" class="cell" data-execution_count="9">
<div id="counts-summary" class="cell-output cell-output-display" data-execution_count="9">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Item</th>
<th data-quarto-table-cell-role="th">Label</th>
<th data-quarto-table-cell-role="th">times_shown</th>
<th data-quarto-table-cell-role="th">times_best</th>
<th data-quarto-table-cell-role="th">times_worst</th>
<th data-quarto-table-cell-role="th">pct_best</th>
<th data-quarto-table-cell-role="th">pct_worst</th>
<th data-quarto-table-cell-role="th">score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>9</td>
<td>MGTA 495 Marketing Analytics (Spring with Yavo...</td>
<td>274</td>
<td>147</td>
<td>12</td>
<td>0.536496</td>
<td>0.043796</td>
<td>0.492701</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>5</td>
<td>MGTA 453 Business Analytics (Fall with August)</td>
<td>270</td>
<td>93</td>
<td>55</td>
<td>0.344444</td>
<td>0.203704</td>
<td>0.140741</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>7</td>
<td>MGTA 455 Customer Analytics (Winter with Nijs)</td>
<td>276</td>
<td>104</td>
<td>71</td>
<td>0.376812</td>
<td>0.257246</td>
<td>0.119565</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>4</td>
<td>MGTA 452 Large Data (Fall with Hansen)</td>
<td>276</td>
<td>77</td>
<td>60</td>
<td>0.278986</td>
<td>0.217391</td>
<td>0.061594</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>8</td>
<td>MGTA 454 Capstone Project (Spring with Advisor)</td>
<td>272</td>
<td>72</td>
<td>69</td>
<td>0.264706</td>
<td>0.253676</td>
<td>0.011029</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>2</td>
<td>MGTA 464 SQL (Summer with Nijs)</td>
<td>274</td>
<td>55</td>
<td>56</td>
<td>0.200730</td>
<td>0.204380</td>
<td>-0.003650</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>10</td>
<td>MGTA 457 Biz. Intelligence Systems (Fall with ...</td>
<td>266</td>
<td>23</td>
<td>55</td>
<td>0.086466</td>
<td>0.206767</td>
<td>-0.120301</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>1</td>
<td>MGTA 403 AI Math, Prog., &amp; Analytics (Summer w...</td>
<td>273</td>
<td>33</td>
<td>90</td>
<td>0.120879</td>
<td>0.329670</td>
<td>-0.208791</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>3</td>
<td>MGTA 451 Marketing/Finance/Operations (Summer ...</td>
<td>272</td>
<td>43</td>
<td>101</td>
<td>0.158088</td>
<td>0.371324</td>
<td>-0.213235</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>6</td>
<td>MGTA 444 Analytics Consulting (Winter with Pet...</td>
<td>267</td>
<td>33</td>
<td>111</td>
<td>0.123596</td>
<td>0.415730</td>
<td>-0.292135</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="cell-counts-plot" class="cell" data-execution_count="10">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/counts-plot-output-1.png" id="counts-plot" width="946" height="566" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The counts-based analysis provides a simple descriptive ranking of the 10 MSBA classes. MGTA 495 Marketing Analytics stands out as the most preferred class by a wide margin, with the highest net best-minus-worst score in the dataset. MGTA 453 Business Analytics and MGTA 455 Customer Analytics also have positive net scores, suggesting that they are chosen as best more often than as worst.</p>
<p>At the other end of the ranking, MGTA 444 Analytics Consulting has the lowest net score, followed by MGTA 451 Marketing/Finance/Operations and MGTA 403 AI Math, Prog., &amp; Analytics. These classes are selected as worst more often than best in the aggregate data. Some classes, such as MGTA 454 Capstone Project and MGTA 464 SQL, lie close to zero, indicating relatively balanced best and worst selection rates.</p>
<p>This counts-based approach is intuitive and useful as a first summary, but it is still limited. It treats the net best-minus-worst score as the final answer and does not account for the full multinomial choice structure of the MaxDiff tasks. To move from descriptive summaries to a model-based estimate of latent class preference, the next step is to convert each MaxDiff screen into a set of choice observations for the multinomial logit model.</p>
</section>
<section id="from-maxdiff-data-to-mnl-choices" class="level2">
<h2 class="anchored" data-anchor-id="from-maxdiff-data-to-mnl-choices">From MaxDiff Data to MNL Choices</h2>
<p>To estimate a multinomial logit model, I need to reorganize the MaxDiff data into choice-format observations. Each respondent-task screen contains 4 alternatives, and the respondent identifies one as best and one as worst. I therefore construct two sets of choice observations from each screen: one for the best choice and one for the worst choice.</p>
<p>In the best-choice dataset, the chosen alternative is the item marked as best on that screen. In the worst-choice dataset, the chosen alternative is the item marked as worst. This transformation allows me to estimate item-level utility parameters using the same MNL logic discussed in class: each task becomes a discrete choice problem over a small set of alternatives.</p>
<div id="choice-check" class="cell" data-execution_count="15">
<div class="cell-output cell-output-stdout">
<pre><code>                             choice_id                 Record ID  Task  \
0  69fb85fbd66b452e6decf4f7_task1_best  69fb85fbd66b452e6decf4f7     1   
1  69fb85fbd66b452e6decf4f7_task1_best  69fb85fbd66b452e6decf4f7     1   
2  69fb85fbd66b452e6decf4f7_task1_best  69fb85fbd66b452e6decf4f7     1   
3  69fb85fbd66b452e6decf4f7_task1_best  69fb85fbd66b452e6decf4f7     1   
4  69fb85fbd66b452e6decf4f7_task2_best  69fb85fbd66b452e6decf4f7     2   
5  69fb85fbd66b452e6decf4f7_task2_best  69fb85fbd66b452e6decf4f7     2   
6  69fb85fbd66b452e6decf4f7_task2_best  69fb85fbd66b452e6decf4f7     2   
7  69fb85fbd66b452e6decf4f7_task2_best  69fb85fbd66b452e6decf4f7     2   

   Position  Item  chosen  is_worst_stage  \
0         1     5       0               0   
1         2     7       1               0   
2         3     4       0               0   
3         4     1       0               0   
4         1     8       0               0   
5         2     3       0               0   
6         3    10       1               0   
7         4     9       0               0   

                                               Label  
0     MGTA 453 Business Analytics (Fall with August)  
1     MGTA 455 Customer Analytics (Winter with Nijs)  
2             MGTA 452 Large Data (Fall with Hansen)  
3  MGTA 403 AI Math, Prog., &amp; Analytics (Summer w...  
4    MGTA 454 Capstone Project (Spring with Advisor)  
5  MGTA 451 Marketing/Finance/Operations (Summer ...  
6  MGTA 457 Biz. Intelligence Systems (Fall with ...  
7  MGTA 495 Marketing Analytics (Spring with Yavo...  
                                     n_rows  n_chosen
choice_id                                            
69fb85fbd66b452e6decf4f7_task1_best       4         1
Number of choice sets: 1360
Total rows in choice-format data: 5440</code></pre>
</div>
</div>
<p>The transformed dataset contains one row per alternative within a choice set. Since each respondent completes 8 tasks and each task contributes both a best-choice and a worst-choice observation, the final choice-format dataset contains 1,360 choice sets and 5,440 rows. A sanity check confirms that every choice set contains exactly 4 alternatives and exactly 1 chosen alternative, which is the structure required for the MNL model.</p>
</section>
<section id="mnl-via-maximum-likelihood" class="level2">
<h2 class="anchored" data-anchor-id="mnl-via-maximum-likelihood">MNL via Maximum Likelihood</h2>
<p>To move beyond simple net best-minus-worst counts, I next fit a multinomial logit (MNL) model to the choice-format data. In this model, each class has an underlying utility parameter, and the probability that a class is chosen from a given screen depends on the exponential of its utility relative to the other classes shown on that screen.</p>
<p>Because only utility differences matter in the MNL model, one item must be normalized as a baseline. I therefore estimate utilities for 9 classes and set the remaining class’s utility to 0. The resulting parameters can be interpreted as relative preference weights on a latent utility scale.</p>
<div id="mnl-loglike" class="cell" data-execution_count="20">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> mnl_loglikelihood(beta):</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>    u <span class="op">=</span> build_utility_vector(beta)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    ll <span class="op">=</span> <span class="fl">0.0</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> items, chosen, stage <span class="kw">in</span> <span class="bu">zip</span>(choice_items, chosen_items, choice_stage):</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>        items <span class="op">=</span> np.array(items)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> stage <span class="op">==</span> <span class="dv">0</span>:   <span class="co"># best stage</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>            utilities <span class="op">=</span> u[items]</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>            chosen_utility <span class="op">=</span> u[chosen]</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>        <span class="cf">else</span>:            <span class="co"># worst stage</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>            utilities <span class="op">=</span> <span class="op">-</span>u[items]</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>            chosen_utility <span class="op">=</span> <span class="op">-</span>u[chosen]</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>        ll <span class="op">+=</span> chosen_utility <span class="op">-</span> logsumexp(utilities)</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> ll</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="cell-mle-results-table" class="cell" data-execution_count="22">
<div id="mle-results-table" class="cell-output cell-output-display" data-execution_count="22">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Item</th>
<th data-quarto-table-cell-role="th">mle_utility</th>
<th data-quarto-table-cell-role="th">Label</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>9</td>
<td>1.585293</td>
<td>MGTA 495 Marketing Analytics (Spring with Yavo...</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>5</td>
<td>0.678173</td>
<td>MGTA 453 Business Analytics (Fall with August)</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>7</td>
<td>0.617829</td>
<td>MGTA 455 Customer Analytics (Winter with Nijs)</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>4</td>
<td>0.459824</td>
<td>MGTA 452 Large Data (Fall with Hansen)</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>8</td>
<td>0.343256</td>
<td>MGTA 454 Capstone Project (Spring with Advisor)</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>2</td>
<td>0.295267</td>
<td>MGTA 464 SQL (Summer with Nijs)</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>10</td>
<td>0.000000</td>
<td>MGTA 457 Biz. Intelligence Systems (Fall with ...</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>1</td>
<td>-0.215736</td>
<td>MGTA 403 AI Math, Prog., &amp; Analytics (Summer w...</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>3</td>
<td>-0.240336</td>
<td>MGTA 451 Marketing/Finance/Operations (Summer ...</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>6</td>
<td>-0.437479</td>
<td>MGTA 444 Analytics Consulting (Winter with Pet...</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="cell-mle-plot" class="cell" data-execution_count="23">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/mle-plot-output-1.png" id="mle-plot" width="960" height="566" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The MNL estimates provide a model-based ranking of class preference on a latent utility scale. Because the model is identified only up to an additive constant, one class is normalized to zero and all other estimates are interpreted relative to that baseline. Classes with larger positive utility estimates are more likely to be chosen, all else equal, when they appear in a MaxDiff screen.</p>
<p>The MLE-based ranking is broadly consistent with the earlier counts analysis, which is reassuring. MGTA 495 Marketing Analytics remains the most preferred class by a substantial margin, followed by MGTA 453 Business Analytics and MGTA 455 Customer Analytics. At the other end of the ranking, MGTA 444 Analytics Consulting has the lowest estimated utility, with MGTA 451 Marketing/Finance/Operations and MGTA 403 AI Math, Prog., &amp; Analytics also ranking near the bottom.</p>
<p>This consistency suggests that the counts-based summary captured the main preference structure in the data. At the same time, the MNL model is more principled because it uses the full multinomial choice structure of the MaxDiff tasks rather than relying only on net best-minus-worst scores.</p>
</section>
<section id="mnl-via-bayesian-estimation" class="level2">
<h2 class="anchored" data-anchor-id="mnl-via-bayesian-estimation">MNL via Bayesian Estimation</h2>
<p>To contrast the likelihood-based MNL estimates with a Bayesian alternative, I next place a normal prior on the free utility parameters. Specifically, I assume that each estimated class utility follows a (N(0,1)) prior. This prior is centered at zero, which reflects a mild belief that extremely large positive or negative utilities are unlikely before seeing the data.</p>
<p>Under this setup, the posterior is proportional to the likelihood times the prior. Rather than running a full Markov chain Monte Carlo sampler, I compute the maximum a posteriori (MAP) estimate, which is the parameter vector that maximizes the log-posterior. In practice, this is equivalent to maximizing the MNL log-likelihood plus the log of the normal prior density.</p>
<div id="log-prior" class="cell" data-execution_count="25">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> log_prior(beta, sigma<span class="op">=</span><span class="fl">1.0</span>):</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="op">-</span><span class="fl">0.5</span> <span class="op">*</span> np.<span class="bu">sum</span>((beta <span class="op">/</span> sigma) <span class="op">**</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="log-posterior" class="cell" data-execution_count="26">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> log_posterior(beta, sigma<span class="op">=</span><span class="fl">1.0</span>):</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> mnl_loglikelihood(beta) <span class="op">+</span> log_prior(beta, sigma<span class="op">=</span>sigma)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="cell-bayes-results-table" class="cell" data-execution_count="28">
<div id="bayes-results-table" class="cell-output cell-output-display" data-execution_count="28">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Item</th>
<th data-quarto-table-cell-role="th">bayes_utility</th>
<th data-quarto-table-cell-role="th">Label</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>9</td>
<td>1.540458</td>
<td>MGTA 495 Marketing Analytics (Spring with Yavo...</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>5</td>
<td>0.643800</td>
<td>MGTA 453 Business Analytics (Fall with August)</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>7</td>
<td>0.584299</td>
<td>MGTA 455 Customer Analytics (Winter with Nijs)</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>4</td>
<td>0.427987</td>
<td>MGTA 452 Large Data (Fall with Hansen)</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>8</td>
<td>0.312574</td>
<td>MGTA 454 Capstone Project (Spring with Advisor)</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>2</td>
<td>0.265225</td>
<td>MGTA 464 SQL (Summer with Nijs)</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>10</td>
<td>0.000000</td>
<td>MGTA 457 Biz. Intelligence Systems (Fall with ...</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>1</td>
<td>-0.240258</td>
<td>MGTA 403 AI Math, Prog., &amp; Analytics (Summer w...</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>3</td>
<td>-0.264530</td>
<td>MGTA 451 Marketing/Finance/Operations (Summer ...</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>6</td>
<td>-0.459397</td>
<td>MGTA 444 Analytics Consulting (Winter with Pet...</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="cell-bayes-plot" class="cell" data-execution_count="29">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/bayes-plot-output-1.png" id="bayes-plot" width="946" height="566" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The Bayesian MAP estimates are very similar to the MLE estimates, but they incorporate a prior belief that class utilities should not be too extreme before seeing the data. Because the prior is centered at zero, the Bayesian estimates are slightly shrunk toward zero relative to the MLE estimates.</p>
<p>In this application, the Bayesian ranking is almost identical to the MLE ranking. MGTA 495 Marketing Analytics remains the most preferred class, followed by MGTA 453 Business Analytics and MGTA 455 Customer Analytics. At the bottom of the ranking, MGTA 444 Analytics Consulting remains the least preferred class. This similarity suggests that the data are informative enough that the prior does not materially change the main conclusions.</p>
<div id="cell-compare-methods-table" class="cell" data-execution_count="30">
<div id="compare-methods-table" class="cell-output cell-output-display" data-execution_count="30">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Item</th>
<th data-quarto-table-cell-role="th">Label</th>
<th data-quarto-table-cell-role="th">score</th>
<th data-quarto-table-cell-role="th">mle_utility</th>
<th data-quarto-table-cell-role="th">bayes_utility</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>9</td>
<td>MGTA 495 Marketing Analytics (Spring with Yavo...</td>
<td>0.492701</td>
<td>1.585293</td>
<td>1.540458</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>5</td>
<td>MGTA 453 Business Analytics (Fall with August)</td>
<td>0.140741</td>
<td>0.678173</td>
<td>0.643800</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>7</td>
<td>MGTA 455 Customer Analytics (Winter with Nijs)</td>
<td>0.119565</td>
<td>0.617829</td>
<td>0.584299</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>4</td>
<td>MGTA 452 Large Data (Fall with Hansen)</td>
<td>0.061594</td>
<td>0.459824</td>
<td>0.427987</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>8</td>
<td>MGTA 454 Capstone Project (Spring with Advisor)</td>
<td>0.011029</td>
<td>0.343256</td>
<td>0.312574</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>2</td>
<td>MGTA 464 SQL (Summer with Nijs)</td>
<td>-0.003650</td>
<td>0.295267</td>
<td>0.265225</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>10</td>
<td>MGTA 457 Biz. Intelligence Systems (Fall with ...</td>
<td>-0.120301</td>
<td>0.000000</td>
<td>0.000000</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>1</td>
<td>MGTA 403 AI Math, Prog., &amp; Analytics (Summer w...</td>
<td>-0.208791</td>
<td>-0.215736</td>
<td>-0.240258</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>3</td>
<td>MGTA 451 Marketing/Finance/Operations (Summer ...</td>
<td>-0.213235</td>
<td>-0.240336</td>
<td>-0.264530</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>6</td>
<td>MGTA 444 Analytics Consulting (Winter with Pet...</td>
<td>-0.292135</td>
<td>-0.437479</td>
<td>-0.459397</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="comparing-the-three-methods" class="level2">
<h2 class="anchored" data-anchor-id="comparing-the-three-methods">Comparing the Three Methods</h2>
<p>The three approaches tell a broadly similar story, but they differ in what they are designed to do. The counts-based method is the simplest and most transparent: it summarizes each class by how often it is chosen as best minus how often it is chosen as worst. This makes it easy to explain, but it is descriptive rather than model-based.</p>
<p>The MNL maximum-likelihood model is more principled because it uses the full multinomial choice structure of the MaxDiff tasks. It estimates latent utility parameters that rationalize the observed best and worst choices. The Bayesian version adds prior information, which produces estimates that are slightly more conservative through shrinkage toward zero.</p>
<p>In this dataset, all three methods deliver nearly the same ranking. MGTA 495 Marketing Analytics is the clear leader, followed by MGTA 453 Business Analytics and MGTA 455 Customer Analytics. At the other end, MGTA 444 Analytics Consulting consistently ranks last. This agreement across methods increases confidence that the main preference ordering is robust rather than an artifact of one particular estimation approach.</p>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">Discussion</h2>
<p>Overall, the analysis suggests a clear preference ordering across the 10 MSBA classes. Across the descriptive counts analysis and both model-based MNL approaches, MGTA 495 Marketing Analytics appears to be the most preferred class by a substantial margin. MGTA 453 Business Analytics and MGTA 455 Customer Analytics also rank highly across methods, while MGTA 444 Analytics Consulting consistently appears at the bottom of the ranking.</p>
<p>The counts analysis is useful as a fast and intuitive summary, but the MNL models provide a stronger statistical foundation because they explicitly account for the discrete choice structure of MaxDiff tasks. The Bayesian MAP estimates further show how a prior can regularize the utility estimates without fundamentally changing the main ranking in this dataset.</p>
<p>A limitation of this analysis is that it treats preferences as homogeneous across respondents. In reality, students may have very different course preferences, and a richer hierarchical Bayes or mixed logit model could capture that heterogeneity. Still, for the purposes of this assignment, the comparison of counts, MLE, and Bayesian MAP provides a clear illustration of how MaxDiff data can be analyzed at multiple levels of sophistication.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>